### PR TITLE
Create pt-pt.json

### PR DESCRIPTION
**Pull request by waldyrious**
Mostly based on the existing pt-br.json file.

### CODE REVIEW

**Comment by plepe** [comment]
Yeah, a new language! Shouldn't this be only 'pt'? I could also say that 'pt-br' (and further portuguese variants) use 'pt' as fallback language (if a string has not been translated).

**Comment by waldyrious** [comment]
Yes, I wondered if that would be the intended code. I believe it depends on the localization system, or ultimately in the implementer if they have the option to set fallback chains manually. If you're OK with using simply "pt", that's my preference as well.

**Comment by waldyrious** [comment]
By the way, does the localization system support language fallbacks defined as graphs rather than chains? (Or more simply, each language having a single fallback language, and then default to English?) That way e.g. "pt" could fall back to pt-br, and vice-versa.

**Comment by plepe** [comment]
Thanks!

**Comment by plepe** [comment]
No, currently it's not possible to have pt-br as fallback to pt and vice-versa. I'll think about that. But I defined 'pt' as fallback of 'pt-br': https://github.com/plepe/modulekit-lang/commit/94bc48a32f25016c3b9400f307aa02f4219c415d

**Comment by IgorEliezer** [comment]
pt-br is to pt as en-us is to en in terms of "lift" vs. "elevator",  "learnt" vs. "learned" and "color" vs. "colour". I prefer pt as fallback if you ask me. I for one can read "European" Portuguese just fine.

The only issue is that some technical therms for administrative areas, transit, zoning, urban typology etc may differ.

@waldyrious, thanks for fixing my (funny) typo. :D

**Comment by waldyrious** [comment]
> I prefer pt as fallback if you ask me.

To clarify, I wasn't suggesting to swap the fallback direction, but to make both languages mutually fall back to each other. That way if term A is translated in pt but not in pt-br, and term B is translated in pt-br and not in pt, users of both localizations would see a Portuguese term (even if it might be an unusual one for them).

> @waldyrious, thanks for fixing my (funny) typo.

That's what open source is for :) "given enough eyeballs..."

**Pull request merged**
