### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by severinmenard**

### CODE REVIEW

**Comment by severinmenard** [comment]
looking for the other strings in French. Eg I would like to change Mémoriaux by Monuments

**Comment by plepe** [comment]
That's in the openstreetmap-tag-translations repo. See: https://wiki.openstreetmap.org/wiki/OpenStreetBrowser/Howto_translate

Thanks for your contributions, btw :-)

**Comment by plepe** [comment]
French is almost finished though, user @Cybereric was very busy :)

**Comment by plepe** [comment]
Here you can see an overview of the completeness of translations: https://wiki.openstreetmap.org/wiki/OpenStreetBrowser/Languages

**Pull request merged**
