### PR TITLE
Update pt-br.json

### PR DESCRIPTION
**Pull request by IgorEliezer**
Add missing entries.

### CODE REVIEW

**Comment by plepe** [comment]
Thanks for your contribution? Do you already know [Weblate](https://weblate.openstreetbrowser.org/projects/openstreetbrowser/)? It's easier for translation. Also, I do no longer add empty strings to the translation files, as Weblate uses the English strings as base. If you want to continue to contribute via Github, I can create the empty strings for you.

**Comment by IgorEliezer** [comment]
> If you want to continue to contribute via Github, I can create the empty strings for you.

Please.

> Do you already know Weblate?

I do, for instance I use it integrated with my GitHub account to contribute to OsmAnd.

Since pt-br OSB was almost 95% translated, I thought it wasn't worth creating another account and I kept using GitHub only.

**Comment by IgorEliezer** [comment]
> Please, if not too much trouble.

Nevermind. I'm in.

**Comment by plepe** [comment]
Cool :-)

**Pull request merged**
