### PR TITLE
Added some missing string translations

### PR DESCRIPTION
**Pull request by strebski**

### CODE REVIEW

**Comment by plepe** [comment]
Thanks for your contribution!

**Comment by strebski** [comment]
@plepe

I see some strings missing both on Weblate and Github so cannot be translated. On OSB in GUI we have also 'Code', 'About'; in Options: 'Debug mode', 'Cancel' button, '-please select-' for base map selection.
Could you add these strings? Thanks! :-)

**Comment by plepe** [comment]
Thanks for notifying. I just added these strings.

**Comment by strebski** [comment]
Finished :-)

**Comment by plepe** [comment]
There's one more source for translatable strings: https://github.com/plepe/openstreetmap-date-format - but it is a bit more complex and needs some actual coding. Check the https://github.com/plepe/openstreetmap-date-format/blob/master/HOWTO_CONTRIBUTE.md file for documentation.

**Pull request merged**
